[RHO-4290] Consolidate logging interface to require channel to be specified
series-ai/logger-lib pull request #1
Opened 2024-09-20 18:36 UTC by jpersons-series

#### Description

Consolidated the log methods such that logging to default without specifying a channel is no longer an option.

Now it looks like:
![image](https://github.com/user-attachments/assets/5d9bdb6c-8cd6-4778-b220-5b7ab45b7c5e)

#### Testing plan

Case by case basis, we will need to rollout one-by-one and case by case basis

#### JIRA + Optional Slack context

https://series-ai.atlassian.net/browse/RHO-4290
https://seriesai.slack.com/archives/C04QCDML1AR/p1726674375358839

2024-09-20 18:52 UTC, kadak4 requested changes

2024-09-20 18:52 UTC, kadak4 commented on PadoruLogger/Debug.cs
> +            LogWarning($"Tried to use Padoru.Diagnostics.Debug without configuring it first. Logger auto-configured itself with default options.", "LogInternal");
This channel should be a constant and called something more informative like `PadoruDebug`

2024-09-20 18:52 UTC, kadak4 commented on PadoruLogger/Debug.cs
> -        public static void LogException(Exception e)
We should keep this overload, no reason to sent null as the messageHeader if we do not want one

2024-09-20 18:52 UTC, kadak4 commented on PadoruLogger/Debug.cs
> -        public static void LogException(object messageHeader, Exception e)
Same here, context is something we rarely have, we should keep this overload

2024-09-20 18:52 UTC, kadak4 commented on PadoruLogger/Debug.cs
> -        public static void LogException(Exception e, object context)
Same here

2024-09-20 18:52 UTC, kadak4 commented on PadoruLogger/Debug.cs
> -        public static void LogException(object messageHeader, Exception e, object context)
Same here

2024-09-23 21:41 UTC, closed without merging

2024-09-23 21:46 UTC, jpersons-series commented
New PR: https://github.com/series-ai/logger-lib/compare/main...jpersons/RHO-4290_require-log-channel?expand=1